In [16]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
iris = load_iris()
X = iris.data
y = iris.target

vectorizer = CountVectorizer()
X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size=0.30, random_state=42)

# corpus = [
#      'This is the first document. ',
#     'This document is the second document.',
#     'And this is the third one.'
#  ]

# z = vectorizer.fit_transform(corpus)
# print(z.toarray())
# print(vectorizer.get_feature_names())
# z

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [18]:
clf = LogisticRegression().fit(X_train,y_train)

/Users/het/Desktop/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/het/Desktop/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [19]:
pridected = clf.predict(X_test)
pridected

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2, 1, 0,
       0])

In [20]:
accuracy = accuracy_score(y_test,pridected)
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [21]:
confusion_matrix(y_test,pridected)

array([[19,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 13]])

In [22]:
print(classification_report(y_test,pridected))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

